#!/usr/bin/env python3
"""
fix-seo-meta.py
---------------
Adds canonical URL + Open Graph + Twitter Card tags to the public pages
that the production-readiness check flagged.

Idempotent: running it twice does not duplicate tags. Each insertion is
guarded by a check that the marker comment does not already exist.

Usage:
    python3 scripts/fix-seo-meta.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SITE = "https://pilotsalesdistribution.com"

# path → file. Same as REQUIRED_PAGES minus the private ones.
PUBLIC_PAGES = {
    "/": "index.html",
    "/products": "products.html",
    "/product-detail": "product-detail.html",
    "/rfq": "rfq.html",
    "/about": "about.html",
    "/contact": "contact.html",
    "/help-center": "help-center.html",
    "/privacy": "privacy.html",
    "/terms": "terms.html",
}

# Per-page SEO data
SEO = {
    "index.html": {
        "title": "Pilot Sales Distribution - Wholesale Inventory. Verified Before You Buy.",
        "description": "Wholesale Inventory. Verified Before You Buy. Confirmed availability, freight quoted per product, and RFQ-first purchasing for serious bulk buyers.",
    },
    "products.html": {
        "title": "Verified Wholesale Products - Pilot Sales Distribution",
        "description": "Browse our curated catalog of verified wholesale products. Real-time availability, freight quoted per product, no surprises.",
    },
    "product-detail.html": {
        "title": "Product Details - Pilot Sales Distribution",
        "description": "Detailed wholesale product information, availability, lead time, and freight quote.",
    },
    "rfq.html": {
        "title": "Request for Quote (RFQ) - Pilot Sales Distribution",
        "description": "Submit a Request for Quote on bulk wholesale products. Get pricing, freight, and lead times from verified suppliers.",
    },
    "about.html": {
        "title": "About - Pilot Sales Distribution",
        "description": "Pilot Sales Distribution is a verified B2B wholesale marketplace. Learn about our trade assurance, escrow, and supplier verification.",
    },
    "contact.html": {
        "title": "Contact - Pilot Sales Distribution",
        "description": "Get in touch with Pilot Sales Distribution. Phone, email, WhatsApp, and contact form for buyers and sellers.",
    },
    "help-center.html": {
        "title": "Help Center - Pilot Sales Distribution",
        "description": "Find answers to common questions about ordering, shipping, RFQs, payments, and account management.",
    },
    "privacy.html": {
        "title": "Privacy Policy - Pilot Sales Distribution",
        "description": "How Pilot Sales Distribution collects, uses, and protects your data. GDPR-compliant privacy practices.",
    },
    "terms.html": {
        "title": "Terms & Conditions - Pilot Sales Distribution",
        "description": "The terms and conditions for using Pilot Sales Distribution. Buyer obligations, seller obligations, and dispute resolution.",
    },
}

OG_IMAGE = f"{SITE}/logo.webp"

MARKER = "<!-- SEO:OG:AUTOGENERATED -->"


def build_block(path: str, title: str, description: str) -> str:
    url = SITE + path
    return f"""{MARKER}
    <link rel="canonical" href="{url}" />
    <meta name="robots" content="index, follow" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="{title}" />
    <meta property="og:description" content="{description}" />
    <meta property="og:url" content="{url}" />
    <meta property="og:image" content="{OG_IMAGE}" />
    <meta property="og:site_name" content="Pilot Sales Distribution" />
    <meta property="og:locale" content="en_US" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="{title}" />
    <meta name="twitter:description" content="{description}" />
    <meta name="twitter:image" content="{OG_IMAGE}" />
"""


def update_page(path: str, fname: str) -> bool:
    """Add SEO block to fname. Returns True if changed."""
    f = REPO / fname
    if not f.exists():
        print(f"  skip {fname} (missing)")
        return False
    text = f.read_text(encoding="utf-8", errors="replace")
    if MARKER in text:
        # Already done; replace the existing block to keep it in sync
        text = re.sub(
            re.escape(MARKER) + r".*?</meta>\s*",
            build_block(path, SEO[fname]["title"], SEO[fname]["description"]).rstrip() + "\n    ",
            text, count=1, flags=re.S
        )
    else:
        # Insert just after the <title>...</title> line
        block = build_block(path, SEO[fname]["title"], SEO[fname]["description"])
        text = re.sub(
            r"(<title>.*?</title>)",
            r"\1\n    " + block.rstrip(),
            text, count=1
        )
    f.write_text(text, encoding="utf-8")
    return True


def main() -> int:
    changed = 0
    for path, fname in PUBLIC_PAGES.items():
        if update_page(path, fname):
            print(f"  ✓ {fname} → {path}")
            changed += 1
    print(f"\nUpdated {changed} pages with canonical + OG + Twitter tags.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
